Description: >
  Udagram Project / Udacity

Parameters:
  EnvironmentName:
    Description: Env Name that will be prefixed in order to access Variables exported from our networking Resources
    Type: String

Resources:
  UdacityS3ReadOnlyEC2:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  IAMWebAppS3IP:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: "UdacityS3ReadOnlyEC2"

Outputs:
  UdacityS3ReadOnlyEC2:
    Description: "Allow EC2 instances to manage Web App S3"
    Value: !Ref IAMWebAppS3IP
    Export:
      Name: !Sub ${EnvironmentName}-IAM-NAME
  UdacityS3ReadOnlyEC2Arn:
    Description: Iam Instance Profile Arn
    Value: !GetAtt UdacityS3ReadOnlyEC2.Arn
    Export:
      Name: !Sub ${EnvironmentName}-IAM-ARN
